/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.filter;

import com.iontorrent.karyo.data.FeatureMetaInfo.Range;
import com.iontorrent.karyo.data.KaryoTrack;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Chantal
 */
public class ScoreFilterPanel extends FilterPanel {

    /**
     * Creates new form ScoreFilterPanel
     */
    public ScoreFilterPanel(String name, KaryoFilter filter, KaryoTrack track) {
        super(filter, track);
        
        initComponents();
        this.jLabel1.setName(name);
        Range r = track.getMetaInfo().getRangeForAttribute("Score");
        p("Range for "+track.getName()+" is:"+r);
        SpinnerNumberModel model = (SpinnerNumberModel) this.smin.getModel();
        model.setMaximum(r.max);
        model.setMinimum(r.min);
        Double step = new Double((r.max - r.min) / 100);
        model.setStepSize(step);
        
        model = (SpinnerNumberModel) this.smax.getModel();
        model.setMaximum(r.max);
        model.setMinimum(r.min);
        
        model.setStepSize(step);
    
    }
    private void p(String s) {
        System.out.println("ScoreFilterPanel:"+s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        smin = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        smax = new javax.swing.JSpinner();

        smin.setModel(new javax.swing.SpinnerNumberModel());

        jLabel1.setText(org.openide.util.NbBundle.getMessage(ScoreFilterPanel.class, "ScoreFilterPanel.jLabel1.text")); // NOI18N

        smax.setModel(new javax.swing.SpinnerNumberModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smin, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(smax, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(smin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(smax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner smax;
    private javax.swing.JSpinner smin;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateFilter() {
        Range r = new Range();
        
        double min = ((Number) (smin.getValue())).doubleValue();
        double max = ((Number) (smax.getValue())).doubleValue();
        r.min = min;
        r.max = max;
        p("Updating LocusScore filter with range "+r);
        ((LocusScoreFilter) filter).setRange(r);
    }
}
