/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.filter;

import com.iontorrent.karyo.data.FeatureMetaInfo;
import com.iontorrent.karyo.data.FeatureTree;
import com.iontorrent.karyo.data.KaryoTrack;
import com.iontorrent.karyo.data.Range;
import com.iontorrent.karyo.filter.VariantAttributeFilter;
import java.util.ArrayList;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Chantal Roth
 */
public class VariantAttributePanel extends FilterPanel {

    /**
     * Creates new form VariantAttributePanel
     */
    public VariantAttributePanel(VariantAttributeFilter filter, KaryoTrack track) {
        super(filter, track);
        initComponents();

        String first = null;
        if (meta != null) {
            boxNames.removeAllItems();
            for (String att : meta.getAttributes()) {
                this.boxNames.addItem(att);
                if (first == null) first = att;
            }
        }
        boxNames.setSelectedItem(first);
        
    }

    public String getSelectedAtt() {
        return (String) boxNames.getSelectedItem();
    }

    public String getSelectedValue() {
        return (String) boxVals.getSelectedItem();
    }

    @Override
    public void updateFilter() {
        ((VariantAttributeFilter)filter).setAttname(getSelectedAtt());
        if (boxVals.isVisible()) {
            ((VariantAttributeFilter)filter).setAttvalue(getSelectedValue());
        }
        else {
            Number num = (Number) spinner.getValue();
            ((VariantAttributeFilter)filter).setAttvalue(num.toString());
            String op = boxOp.getSelectedItem().toString().trim();
            ((VariantAttributeFilter)filter).setOperator(op);
        }
    }

    private void updateValues(String att) {
        if (meta != null) {
            if (meta.isRange(att)) {
                boxVals.setVisible(false);
                FeatureMetaInfo.Range r = meta.getRangeForAttribute(att);
                p("Got range: "+r);
                this.txtValue.setVisible(false);
                SpinnerNumberModel model = (SpinnerNumberModel) spinner.getModel();
                model.setMaximum(r.max);
                model.setMinimum(r.min);
                p("Model min is set to "+model.getMinimum());
                p("Model max is set to "+model.getMaximum());
                model.setValue(model.getMinimum());
                Double step = new Double((r.max-r.min)/100);
                p("Model step is set to "+step);
                model.setStepSize(step);
            }
            else {
                ArrayList<String> vals = meta.getValuesForAttribute(att);
                spinner.setVisible(false);
                this.boxOp.setVisible(false);
                this.txtValue.setVisible(false);
                if (vals != null) {
                    this.boxVals.removeAllItems();
                    for (String val : vals) {
                        this.boxVals.addItem(val);
                    }
                }
            }
        }
    }
    private void p(String s){
        System.out.println("VariantAttributePanel: "+s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        boxNames = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        boxVals = new javax.swing.JComboBox();
        txtValue = new javax.swing.JTextField();
        spinner = new javax.swing.JSpinner();
        boxOp = new javax.swing.JComboBox();

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(VariantAttributePanel.class, "VariantAttributePanel.jLabel1.text")); // NOI18N

        boxNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "REF (reference bases)", "ALT (alternate non-reference alleles)", "QUAL (phred scaled quality)", "FILTER (pass or list of fllters that failedd)", "AA (ancestral allele)", "AC (allele count in genotypes)", "AF (alle frequency)", "AN (total nr of alleles in called genotypes)", "VT (variant type)", " " }));
        boxNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNamesActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(VariantAttributePanel.class, "VariantAttributePanel.jLabel2.text")); // NOI18N

        txtValue.setText(org.openide.util.NbBundle.getMessage(VariantAttributePanel.class, "VariantAttributePanel.txtValue.text")); // NOI18N

        spinner.setModel(new javax.swing.SpinnerNumberModel());

        boxOp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", ">", "<", "<>" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNames, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxVals, 0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(boxNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(boxVals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxOp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 132, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boxNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNamesActionPerformed
        String sel = (String) this.boxNames.getSelectedItem();
        if (sel != null) {
            this.updateValues(sel);
        }

    }//GEN-LAST:event_boxNamesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxNames;
    private javax.swing.JComboBox boxOp;
    private javax.swing.JComboBox boxVals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner spinner;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
