/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.views.karyo;

import com.iontorrent.data.karyo.FeatureMetaInfo;
import com.iontorrent.data.karyo.FeatureTree;
import com.iontorrent.data.karyo.KaryoTrack;
import com.iontorrent.data.karyo.filter.VariantAttributeFilter;
import java.util.ArrayList;

/**
 *
 * @author Chantal Roth
 */
public class VariantAttributePanel extends FilterPanel {

    /**
     * Creates new form VariantAttributePanel
     */
    public VariantAttributePanel(VariantAttributeFilter filter, KaryoTrack track) {
        super(filter, track);
        initComponents();

        if (meta != null) {
            boxNames.removeAllItems();
            for (String att : meta.getAttributes()) {
                this.boxNames.addItem(att);
            }
        }
    }

    public String getSelectedAtt() {
        return (String) boxNames.getSelectedItem();
    }

    public String getSelectedValue() {
        return (String) boxVals.getSelectedItem();
    }

    @Override
    public void updateFilter() {
        ((VariantAttributeFilter)filter).setAttname(getSelectedAtt());
        ((VariantAttributeFilter)filter).setAttvalue(getSelectedValue());
    }

    private void updateValues(String att) {
        if (meta != null) {
            ArrayList<String> vals = meta.getValuesForAttribute(att);
            if (vals != null) {
                this.boxVals.removeAllItems();
                for (String val : vals) {
                    this.boxVals.addItem(val);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        boxNames = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        boxVals = new javax.swing.JComboBox();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(VariantAttributePanel.class, "VariantAttributePanel.jLabel1.text")); // NOI18N

        boxNames.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "REF (reference bases)", "ALT (alternate non-reference alleles)", "QUAL (phred scaled quality)", "FILTER (pass or list of fllters that failedd)", "AA (ancestral allele)", "AC (allele count in genotypes)", "AF (alle frequency)", "AN (total nr of alleles in called genotypes)", "VT (variant type)", " " }));
        boxNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNamesActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(VariantAttributePanel.class, "VariantAttributePanel.jLabel2.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxNames, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boxVals, 0, 139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(boxNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(boxVals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void boxNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNamesActionPerformed
        String sel = (String) this.boxNames.getSelectedItem();
        if (sel != null) {
            this.updateValues(sel);
        }

    }//GEN-LAST:event_boxNamesActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox boxNames;
    private javax.swing.JComboBox boxVals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
