/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.cnv;

import com.iontorrent.karyo.views.KaryoManager;
import javax.swing.JFrame;
import org.broad.igv.ui.IGV;

/**
 *
 * @author Chantal
 */
public class CnvControlPanel extends javax.swing.JPanel {

    CnvData data;
    CnvPanel cnvpanel;
    /**
     * Creates new form CnvControlPanel
     */
    public CnvControlPanel(CnvData data) {
        this.data = data;
        cnvpanel = new CnvPanel(KaryoManager.getManager(IGV.getMainFrame(), null), data);
        initComponents();
        add("Center", cnvpanel);
    }
    
    public static void show(CnvData data) {
        CnvControlPanel cnv = new CnvControlPanel(data);
        JFrame f = new JFrame("CNV Whole Genome Plot");
        f.setSize(1200, 800);
        if (IGV.getMainFrame().getIconImage() != null) {
            f.setIconImage(IGV.getMainFrame().getIconImage());
        }
        
        f.getContentPane().add(cnv);
        f.setVisible(true);
        f.toFront();        
        f.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnExport = new javax.swing.JButton();

        jButton1.setText(org.openide.util.NbBundle.getMessage(CnvControlPanel.class, "CnvControlPanel.jButton1.text")); // NOI18N

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        btnExport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iontorrent/views/save.png"))); // NOI18N
        btnExport.setText(org.openide.util.NbBundle.getMessage(CnvControlPanel.class, "CnvControlPanel.btnExport.text")); // NOI18N
        btnExport.setToolTipText(org.openide.util.NbBundle.getMessage(CnvControlPanel.class, "CnvControlPanel.btnExport.toolTipText")); // NOI18N
        btnExport.setFocusable(false);
        btnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExport);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        IGV igv = IGV.getInstance();
        igv.saveImage(cnvpanel);
    }//GEN-LAST:event_btnExportActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExport;
    private javax.swing.JButton jButton1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
