/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.views;

import com.iontorrent.karyo.data.KaryoTrack;
import com.iontorrent.karyo.renderer.RenderType;
import java.awt.Color;
import javax.swing.JColorChooser;

/**
 *
 * @author Chantal
 */
public class RenderTypePanel extends javax.swing.JPanel {

    RenderType render;
    KaryoTrack track;
    /**
     * Creates new form RenderTypePanel
     */
    public RenderTypePanel(RenderType render, KaryoTrack track) {
        initComponents();
        this.render = render;
        this.track = track;
        this.lblName.setText("<html><b>"+render.getName()+"</b> for track "+track.getName()+"</html>");
        this.lblDesc.setText("<html>" +render.getDescription()+"</html>");
        this.lblColor.setText(render.getColorName());
        Color c = render.getColor();
        if (c == null) c = render.getDefaultColor(track);
        btnColor.setBackground(c);
       // btnColor.setBackground(c);
        if (render.getColor1Name() != null) {
            lblColor1.setText(render.getColor1Name());
            c = render.getColor1();
            if (c == null) c = render.getDefaultColor1(track);
            btnColor1.setBackground(c);
           // btnColor1.setBackground(c);
        }
        else {
            lblColor1.setVisible(false);;
            btnColor1.setVisible(false);            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblDesc = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblColor = new javax.swing.JLabel();
        lblColor1 = new javax.swing.JLabel();
        btnColor1 = new javax.swing.JButton();
        btnColor = new javax.swing.JButton();

        lblName.setText(org.openide.util.NbBundle.getMessage(RenderTypePanel.class, "RenderTypePanel.lblName.text")); // NOI18N

        lblDesc.setText(org.openide.util.NbBundle.getMessage(RenderTypePanel.class, "RenderTypePanel.lblDesc.text")); // NOI18N

        lblColor.setText(org.openide.util.NbBundle.getMessage(RenderTypePanel.class, "RenderTypePanel.lblColor.text")); // NOI18N

        lblColor1.setText(org.openide.util.NbBundle.getMessage(RenderTypePanel.class, "RenderTypePanel.lblColor1.text")); // NOI18N

        btnColor1.setText(org.openide.util.NbBundle.getMessage(RenderTypePanel.class, "RenderTypePanel.btnColor1.text")); // NOI18N
        btnColor1.setMaximumSize(new java.awt.Dimension(22, 22));
        btnColor1.setMinimumSize(new java.awt.Dimension(22, 22));
        btnColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColor1ActionPerformed(evt);
            }
        });

        btnColor.setText(org.openide.util.NbBundle.getMessage(RenderTypePanel.class, "RenderTypePanel.btnColor.text")); // NOI18N
        btnColor.setMaximumSize(new java.awt.Dimension(22, 22));
        btnColor.setMinimumSize(new java.awt.Dimension(22, 22));
        btnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnColor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblColor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblColor1)
                        .addGap(8, 8, 8))
                    .addComponent(btnColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDesc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorActionPerformed
        Color res= JColorChooser.showDialog(this, "Pick the "+render.getColorName()+" for this track", render.getColor()) ;
        if (res != null) {
            render.setColor(res);
            this.btnColor.setBackground(res);
        }
    }//GEN-LAST:event_btnColorActionPerformed

    private void btnColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColor1ActionPerformed
        Color res= JColorChooser.showDialog(this, "Pick the "+render.getColor1Name()+" for this track", render.getColor1()) ;
        if (res != null) {
            render.setColor1(res);
            this.btnColor1.setBackground(res);
        }
    }//GEN-LAST:event_btnColor1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColor;
    private javax.swing.JButton btnColor1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblColor1;
    private javax.swing.JLabel lblDesc;
    private javax.swing.JLabel lblName;
    // End of variables declaration//GEN-END:variables
}
