/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.views;

import com.iontorrent.karyo.data.KaryoTrack;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Chantal Roth
 */
public class SimpleTrackListPanel extends javax.swing.JPanel {

    KaryoManager man;
    JPanel center;
    KaryoControlPanel control;

    /**
     * Creates new form TrackListPanel
     */
    public SimpleTrackListPanel(KaryoManager man, boolean showDetail, KaryoControlPanel control) {
        this.man = man;
        initComponents();
        center = new JPanel();
        this.control = control;
        int nr = man.getKaryotracks().size();

        center.setLayout(new GridLayout(nr, 1));
        setLayout(new BorderLayout());
        Dimension d = new Dimension(200, 400);
        this.setMinimumSize(d);
        SingleTrackPanel pan = null;
        if (control == null) {
            System.out.println("TrackListPanel:  control is null!");
        }
        for (KaryoTrack t : man.getKaryotracks()) {
            p("Creating single track panel for " + t.getTrackDisplayName() + ": visible=" + t.isVisible());

            pan = new SingleTrackPanel(t, false, control, null);

            center.add(pan);
        }
        add("Center", center);
        if (!showDetail) {
            if (pan != null) {
                JButton btn = new JButton();
                btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/iontorrent/views/icons/settings.png"))); // NOI18N
                btn.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
 
                        TrackListPanel.show(new ActionListener() {
                            @Override
                            public void actionPerformed(ActionEvent e) {
                                if (SimpleTrackListPanel.this.control != null) {
                                    SimpleTrackListPanel.this.control.recreateView(false);
                                    saveOptions();
                                }
                                
                            }
                        }, SimpleTrackListPanel.this.man, null);

                        // JOptionPane.showMessageDialog(center,, "Here you can change the name and color of the track", JOptionPane.PLAIN_MESSAGE);

                    }
                });
                add("South", btn);
            }
        }


    }
    private void saveOptions() {
        this.man.saveGuiProperties();
    }
    private void p(String s) {
        System.out.println("SimpleTrackListPanel: " + s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(SimpleTrackListPanel.class, "SimpleTrackListPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
