/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.views;

import com.iontorrent.karyo.data.KaryoTrack;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Chantal Roth
 */
public class TrackListPanel extends javax.swing.JPanel {

    KaryoManager man;
    //  JPanel center;
    KaryoControlPanel control;
    TrackOptionsPanel options;
    KaryoTrack curTrack;
    JList list;

    /**
     * Creates new form TrackListPanel
     */
    public TrackListPanel(KaryoManager man, KaryoControlPanel control) {
        this.man = man;
        initComponents();
        //   center= new JPanel();
        this.control = control;
        int nr = man.getKaryotracks().size();

        // center.setLayout(new GridLayout(nr, 1));
        setLayout(new BorderLayout());

        if (control == null) {
            System.out.println("TrackListPanel:  control is null!");
        }
        DefaultListModel model = new DefaultListModel();
        list = new JList(model);
        list.setPreferredSize(new Dimension(150, 200));
        list.setMinimumSize(new Dimension(150, 200));

        for (KaryoTrack t : man.getKaryotracks()) {
            p("Creating single track panel for " + t.getName() + ": visible=" + t.isVisible());
            if (curTrack == null) {
                curTrack = t;
            }
            model.addElement(t);


        }
        if (man.getKaryoTracks().size() > 0) {
            list.setSelectedIndex(0);
        }
        list.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                options.updateTrack();
                curTrack = (KaryoTrack) list.getSelectedValue();
                p("Got a list selection event: " + curTrack);
                updateOptions();
            }
        });
        add("Center", list);
        updateOptions();

    }

    public static void show(final ActionListener listener, KaryoManager manager, KaryoControlPanel control) {
//        final JDialog d = new JDialog();
//        d.setModal(false);
            TrackListPanel tp = new TrackListPanel(manager, control);
//        d.setLayout(new BorderLayout());
//        d.add("Center", tp);
//        d.setVisible(true);
//        d.setAlwaysOnTop(true);
//        d.setAutoRequestFocus(true);
//       
//        JButton ok = new JButton("OK");
//        d.add("South", ok);
//        d.setTitle("Track Rendering Options");
//        d.setSize(500, 400);
//        ok.addActionListener(listener);
//        d.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosing(WindowEvent e) {
//                listener.actionPerformed(null);
//                d.dispose();
//            }
//        });
//        d.pack();
//        d.setSize(800, 600);
//        d.setVisible(true);
        int ans = JOptionPane.showConfirmDialog(control, tp, "Track Rendering Options", JOptionPane.OK_OPTION);
        if (ans == JOptionPane.OK_OPTION) {
            listener.actionPerformed(null);
        }
        
    }

    private void updateOptions() {
        p("Updating options");
        if (options != null) {
            remove(options);
        }
        if (curTrack == null) {
            return;
        }
        options = new TrackOptionsPanel(curTrack);
        add("East", options);
        repaint();
        this.invalidate();
        this.revalidate();
    }

    private void p(String s) {
        System.out.println("TrackListPanel: " + s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, org.openide.util.NbBundle.getMessage(SimpleTrackListPanel.class, "SimpleTrackListPanel.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 181, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 273, Short.MAX_VALUE));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
