/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.views;

import com.iontorrent.karyo.data.KaryoTrack;
import java.awt.Color;

/**
 *
 * @author Chantal
 */
public class TrackOptionsPanel extends javax.swing.JPanel {
    KaryoTrack track;
    RenderOptionsPanel render;
    /**
     * Creates new form TrackOptionsPanel
     */
    public TrackOptionsPanel(KaryoTrack track) {
        initComponents();
        this.track = track;
        this.lblTrack.setText("<html><b><h2>Details for "+track.getName()+"</h2></b></html>");
        setColor(track.getColor());
        this.txtName.setText(track.getName());
        this.txtShort.setText(track.getShortName());
        lblName.setToolTipText(track.toString());
        render = new RenderOptionsPanel(track);
        tab.addTab("Rendering options", render);
    }
    private Color getColor() {
        return colorChooser.getColor();
    }
    public void setColor(Color c) {
        colorChooser.setColor(c);
    }

    private String getTrackName() {
        return txtName.getText();
    }
    public void updateTrack() {
        String n =getTrackName();
        if (n != null && n.length()>0) track.setName(n);
        n =this.txtShort.getText();
        if (n != null && n.length()>0) track.setShortname(n);
        Color c = getColor();
        if (c != null) track.setColor(c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrack = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        panName = new javax.swing.JPanel();
        txtShort = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        colorChooser = new javax.swing.JColorChooser();

        setLayout(new java.awt.BorderLayout());

        lblTrack.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.lblTrack.text")); // NOI18N
        add(lblTrack, java.awt.BorderLayout.PAGE_START);

        txtShort.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.txtShort.text")); // NOI18N

        lblName.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.lblName.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.jLabel1.text")); // NOI18N

        txtName.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.txtName.text")); // NOI18N

        javax.swing.GroupLayout panNameLayout = new javax.swing.GroupLayout(panName);
        panName.setLayout(panNameLayout);
        panNameLayout.setHorizontalGroup(
            panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panNameLayout.setVerticalGroup(
            panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tab.addTab(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.panName.TabConstraints.tabTitle"), panName); // NOI18N
        tab.addTab(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.colorChooser.TabConstraints.tabTitle"), colorChooser); // NOI18N

        add(tab, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTrack;
    private javax.swing.JPanel panName;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtShort;
    // End of variables declaration//GEN-END:variables
}
