/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.iontorrent.karyo.views;

import com.iontorrent.karyo.data.KaryoFeature;
import com.iontorrent.karyo.data.KaryoTrack;
import com.iontorrent.utils.StringTools;
import java.awt.Color;
import org.broad.igv.util.ResourceLocator;
import org.broad.tribble.Feature;

/**
 *
 * @author Chantal
 */
public class TrackOptionsPanel extends javax.swing.JPanel {
    KaryoTrack track;
    RenderOptionsPanel render;
    
    /**
     * Creates new form TrackOptionsPanel
     */
    public TrackOptionsPanel(KaryoTrack track) {
        initComponents();
        
        this.track = track;
        this.lblTrack.setText("<html><b><h2>"+track.getTrackDisplayName()+"</h2></b></html>");
        String source = "Unknown";
        String type = "Unknown";
        ResourceLocator loc = track.getTrack().getResourceLocator();
        if (loc != null) {
            source = loc.getPath();
            source = StringTools.addNL(source, "<br>", 60);
            type = track.getFileExt();
            
        }
        this.lblType.setText(type);
        
        String example = "No example features found";
        Feature f = track.getSampleafeture();
        if (f != null) {
            KaryoFeature kf = new KaryoFeature(f);
            example = "<html>"+kf.toHtml()+"</html>";
        }
        
       
        areaExample.setContentType("text/html");
        this.areaExample.setText(example);
        this.lblSource.setText("<html>"+source+"</html>");
     //   setColor(track.getColor());
        this.txtName.setText(track.getTrackDisplayName());
        this.txtShort.setText(track.getShortName());
        lblName.setToolTipText(track.toString());
        render = new RenderOptionsPanel(track);
       
        tab.addTab("Rendering options", null, render,"Define how this track is rendered");
        //tab.insertTab("Rendering options", null, render,"Define how this track is rendered", 0);
        tab.setSelectedIndex(0);
    }
//    private Color getColor() {
//        return colorChooser.getColor();
//    }
//    public void setColor(Color c) {
//        colorChooser.setColor(c);
//    }

    private String getTrackName() {
        return txtName.getText();
    }
    public void updateTrack() {
        String n =getTrackName();
        if (n != null && n.length()>0) track.setTrackDisplayName(n);
        n =this.txtShort.getText();
        if (n != null && n.length()>0) track.setShortname(n);
//        Color c = getColor();
//        if (c != null) track.setColor(c);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTrack = new javax.swing.JLabel();
        tab = new javax.swing.JTabbedPane();
        panName = new javax.swing.JPanel();
        txtShort = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSource = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblType = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaExample = new javax.swing.JEditorPane();

        setLayout(new java.awt.BorderLayout());

        lblTrack.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.lblTrack.text")); // NOI18N
        add(lblTrack, java.awt.BorderLayout.PAGE_START);

        txtShort.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.txtShort.text")); // NOI18N
        txtShort.setToolTipText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.txtShort.toolTipText")); // NOI18N

        lblName.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.lblName.text")); // NOI18N

        jLabel1.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.jLabel1.text")); // NOI18N

        txtName.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.txtName.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.jLabel2.text")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.jLabel3.text")); // NOI18N

        lblSource.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.lblSource.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.jLabel4.text")); // NOI18N

        lblType.setText(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.lblType.text")); // NOI18N

        jScrollPane2.setViewportView(areaExample);

        javax.swing.GroupLayout panNameLayout = new javax.swing.GroupLayout(panName);
        panName.setLayout(panNameLayout);
        panNameLayout.setHorizontalGroup(
            panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panNameLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panNameLayout.createSequentialGroup()
                        .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panNameLayout.createSequentialGroup()
                                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtShort, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblType))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        panNameLayout.setVerticalGroup(
            panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtShort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSource)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tab.addTab(org.openide.util.NbBundle.getMessage(TrackOptionsPanel.class, "TrackOptionsPanel.panName.TabConstraints.tabTitle"), panName); // NOI18N

        add(tab, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane areaExample;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblSource;
    private javax.swing.JLabel lblTrack;
    private javax.swing.JLabel lblType;
    private javax.swing.JPanel panName;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtShort;
    // End of variables declaration//GEN-END:variables
}
